# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Vivado/Project_Vivado/DoubleDMA/DoubleDMA.srcs/sources_1/bd/DoubleDMA/ip/DoubleDMA_axi_dma_0/DoubleDMA_axi_dma_0.xci
# IP: The module: 'DoubleDMA_axi_dma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado/Project_Vivado/DoubleDMA/DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_axi_dma_0/DoubleDMA_axi_dma_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DoubleDMA_axi_dma_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Vivado/Project_Vivado/DoubleDMA/DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_axi_dma_0/DoubleDMA_axi_dma_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'DoubleDMA_axi_dma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Vivado/Project_Vivado/DoubleDMA/DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_axi_dma_0/DoubleDMA_axi_dma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DoubleDMA_axi_dma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Vivado/Project_Vivado/DoubleDMA/DoubleDMA.srcs/sources_1/bd/DoubleDMA/ip/DoubleDMA_axi_dma_0/DoubleDMA_axi_dma_0.xci
# IP: The module: 'DoubleDMA_axi_dma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado/Project_Vivado/DoubleDMA/DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_axi_dma_0/DoubleDMA_axi_dma_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DoubleDMA_axi_dma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Vivado/Project_Vivado/DoubleDMA/DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_axi_dma_0/DoubleDMA_axi_dma_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'DoubleDMA_axi_dma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Vivado/Project_Vivado/DoubleDMA/DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_axi_dma_0/DoubleDMA_axi_dma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DoubleDMA_axi_dma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
