#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : DoubleDMA.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Sep 05 16:45:58 +0800 2022
# SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: DoubleDMA.sh [-help]
# usage: DoubleDMA.sh [-lib_map_path]
# usage: DoubleDMA.sh [-noclean_files]
# usage: DoubleDMA.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'DoubleDMA.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_8 processing_system7_vip_v1_0_10 xil_defaultlib xbip_utils_v3_0_10 axi_utils_v2_0_6 xbip_pipe_v3_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_dsp48_multadd_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_16 floating_point_v7_1_11 lib_pkg_v1_0_2 fifo_generator_v13_2_5 lib_fifo_v1_0_14 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_datamover_v5_1_24 axi_sg_v4_1_13 axi_dma_v7_1_23 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_22 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 axi_protocol_converter_v2_1_22 axi_clock_converter_v2_1_21 blk_mem_gen_v8_4_4 axi_dwidth_converter_v2_1_22 proc_sys_reset_v5_0_13)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "DoubleDMA.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "E:/Vivado/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "E:/Vivado/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "E:/Vivado/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "E:/Vivado/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "E:/Vivado/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "E:/Vivado/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "E:/Vivado/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "E:/Vivado/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "E:/Vivado/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "E:/Vivado/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "E:/Vivado/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "E:/Vivado/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "E:/Vivado/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_processing_system7_0_0/sim/DoubleDMA_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/d117/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_16 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ce84/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_1_11 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/b0c0/hdl/floating_point_v7_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work floating_point_v7_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/b0c0/hdl/floating_point_v7_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/26e4/hdl/verilog/AirLight_control_s_axi.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/26e4/hdl/verilog/AirLight_dictB.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/26e4/hdl/verilog/AirLight_dmul_64ns_64ns_64_7_max_dsp_1.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/26e4/hdl/verilog/AirLight_mul_32s_32s_32_2_1.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/26e4/hdl/verilog/AirLight_regslice_both.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/26e4/hdl/verilog/AirLight_sdiv_32ns_32ns_32_36_seq_1.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/26e4/hdl/verilog/AirLight_sitodp_32ns_64_6_no_dsp_1.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/26e4/hdl/verilog/AirLight.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/26e4/hdl/ip/AirLight_ap_dmul_5_max_dsp_64.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/26e4/hdl/ip/AirLight_ap_sitodp_4_no_dsp_32.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_AirLight_0_0/sim/DoubleDMA_AirLight_0_0.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/verilog/FinalDehaze_control_s_axi.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/verilog/FinalDehaze_dadd_64ns_64ns_64_7_full_dsp_1.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/verilog/FinalDehaze_dadddsub_64ns_64ns_64_7_full_dsp_1.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/verilog/FinalDehaze_dcmp_64ns_64ns_1_2_no_dsp_1.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/verilog/FinalDehaze_ddiv_64ns_64ns_64_59_no_dsp_1.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/verilog/FinalDehaze_dexp_64ns_64ns_64_21_full_dsp_1.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/verilog/FinalDehaze_dmul_64ns_64ns_64_7_max_dsp_1.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/verilog/FinalDehaze_regslice_both.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/verilog/FinalDehaze_sitodp_32s_64_6_no_dsp_1.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/verilog/FinalDehaze_sitodp_64s_64_6_no_dsp_1.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/verilog/FinalDehaze_uitodp_32ns_64_6_no_dsp_1.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/verilog/FinalDehaze.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/ip/FinalDehaze_ap_dadddsub_5_full_dsp_64.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/ip/FinalDehaze_ap_dadd_5_full_dsp_64.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/ip/FinalDehaze_ap_dcmp_0_no_dsp_64.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/ip/FinalDehaze_ap_ddiv_57_no_dsp_64.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/ip/FinalDehaze_ap_dexp_19_full_dsp_64.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/ip/FinalDehaze_ap_dmul_5_max_dsp_64.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/ip/FinalDehaze_ap_sitodp_4_no_dsp_32.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/ip/FinalDehaze_ap_sitodp_4_no_dsp_64.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/05a7/hdl/ip/FinalDehaze_ap_uitodp_4_no_dsp_32.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_FinalDehaze_0_0/sim/DoubleDMA_FinalDehaze_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_24 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/4ab6/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_13 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/4919/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_23 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/89d8/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_axi_dma_0/sim/DoubleDMA_axi_dma_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_xbar_0/sim/DoubleDMA_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/1304/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/2394/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_auto_us_0/sim/DoubleDMA_auto_us_0.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_auto_us_1/sim/DoubleDMA_auto_us_1.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_auto_us_2/sim/DoubleDMA_auto_us_2.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_auto_pc_0/sim/DoubleDMA_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_rst_ps7_0_100M_0/sim/DoubleDMA_rst_ps7_0_100M_0.vhd" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_axi_dma_0_0/sim/DoubleDMA_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ipshared/34f8/hdl" +incdir+"E:/Vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_xbar_1/sim/DoubleDMA_xbar_1.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/ip/DoubleDMA_auto_pc_1/sim/DoubleDMA_auto_pc_1.v" \
    "$ref_dir/../../../../DoubleDMA.gen/sources_1/bd/DoubleDMA/sim/DoubleDMA.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.DoubleDMA xil_defaultlib.glbl -o DoubleDMA_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./DoubleDMA_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./DoubleDMA.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key DoubleDMA_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc DoubleDMA_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./DoubleDMA.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: DoubleDMA.sh [-help]\n\
Usage: DoubleDMA.sh [-lib_map_path]\n\
Usage: DoubleDMA.sh [-reset_run]\n\
Usage: DoubleDMA.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
