#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("src_TDATA", 8, hls_in, 0, "axis", "in_data", 1),
	Port_Property("src_TVALID", 1, hls_in, 6, "axis", "in_vld", 1),
	Port_Property("src_TREADY", 1, hls_out, 6, "axis", "in_acc", 1),
	Port_Property("src_TKEEP", 1, hls_in, 1, "axis", "in_data", 1),
	Port_Property("src_TSTRB", 1, hls_in, 2, "axis", "in_data", 1),
	Port_Property("src_TUSER", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("src_TLAST", 1, hls_in, 4, "axis", "in_data", 1),
	Port_Property("src_TID", 1, hls_in, 5, "axis", "in_data", 1),
	Port_Property("src_TDEST", 1, hls_in, 6, "axis", "in_data", 1),
	Port_Property("B_A", 32, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("G_A", 32, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("R_A", 32, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("dst_TDATA", 8, hls_out, 10, "axis", "out_data", 1),
	Port_Property("dst_TVALID", 1, hls_out, 16, "axis", "out_vld", 1),
	Port_Property("dst_TREADY", 1, hls_in, 16, "axis", "out_acc", 1),
	Port_Property("dst_TKEEP", 1, hls_out, 11, "axis", "out_data", 1),
	Port_Property("dst_TSTRB", 1, hls_out, 12, "axis", "out_data", 1),
	Port_Property("dst_TUSER", 1, hls_out, 13, "axis", "out_data", 1),
	Port_Property("dst_TLAST", 1, hls_out, 14, "axis", "out_data", 1),
	Port_Property("dst_TID", 1, hls_out, 15, "axis", "out_data", 1),
	Port_Property("dst_TDEST", 1, hls_out, 16, "axis", "out_data", 1),
	Port_Property("s_axi_control_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_AWADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_ARADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "FinalDehaze";
