# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DoubleDMA/DoubleDMA.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DoubleDMA || ORIG_REF_NAME==DoubleDMA} -quiet] -quiet

# IP: bd/DoubleDMA/ip/DoubleDMA_processing_system7_0_0/DoubleDMA_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DoubleDMA_processing_system7_0_0 || ORIG_REF_NAME==DoubleDMA_processing_system7_0_0} -quiet] -quiet

# IP: bd/DoubleDMA/ip/DoubleDMA_AirLight_0_0/DoubleDMA_AirLight_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DoubleDMA_AirLight_0_0 || ORIG_REF_NAME==DoubleDMA_AirLight_0_0} -quiet] -quiet

# IP: bd/DoubleDMA/ip/DoubleDMA_FinalDehaze_0_0/DoubleDMA_FinalDehaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DoubleDMA_FinalDehaze_0_0 || ORIG_REF_NAME==DoubleDMA_FinalDehaze_0_0} -quiet] -quiet

# IP: bd/DoubleDMA/ip/DoubleDMA_axi_dma_0/DoubleDMA_axi_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DoubleDMA_axi_dma_0 || ORIG_REF_NAME==DoubleDMA_axi_dma_0} -quiet] -quiet

# IP: bd/DoubleDMA/ip/DoubleDMA_xbar_0/DoubleDMA_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DoubleDMA_xbar_0 || ORIG_REF_NAME==DoubleDMA_xbar_0} -quiet] -quiet

# IP: bd/DoubleDMA/ip/DoubleDMA_auto_us_0/DoubleDMA_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DoubleDMA_auto_us_0 || ORIG_REF_NAME==DoubleDMA_auto_us_0} -quiet] -quiet

# IP: bd/DoubleDMA/ip/DoubleDMA_auto_us_1/DoubleDMA_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DoubleDMA_auto_us_1 || ORIG_REF_NAME==DoubleDMA_auto_us_1} -quiet] -quiet

# IP: bd/DoubleDMA/ip/DoubleDMA_auto_us_2/DoubleDMA_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DoubleDMA_auto_us_2 || ORIG_REF_NAME==DoubleDMA_auto_us_2} -quiet] -quiet

# IP: bd/DoubleDMA/ip/DoubleDMA_auto_pc_0/DoubleDMA_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DoubleDMA_auto_pc_0 || ORIG_REF_NAME==DoubleDMA_auto_pc_0} -quiet] -quiet

# IP: bd/DoubleDMA/ip/DoubleDMA_axi_mem_intercon_0/DoubleDMA_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DoubleDMA_axi_mem_intercon_0 || ORIG_REF_NAME==DoubleDMA_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/DoubleDMA/ip/DoubleDMA_rst_ps7_0_100M_0/DoubleDMA_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DoubleDMA_rst_ps7_0_100M_0 || ORIG_REF_NAME==DoubleDMA_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/DoubleDMA/ip/DoubleDMA_axi_dma_0_0/DoubleDMA_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DoubleDMA_axi_dma_0_0 || ORIG_REF_NAME==DoubleDMA_axi_dma_0_0} -quiet] -quiet

# IP: bd/DoubleDMA/ip/DoubleDMA_xbar_1/DoubleDMA_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DoubleDMA_xbar_1 || ORIG_REF_NAME==DoubleDMA_xbar_1} -quiet] -quiet

# IP: bd/DoubleDMA/ip/DoubleDMA_auto_pc_1/DoubleDMA_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DoubleDMA_auto_pc_1 || ORIG_REF_NAME==DoubleDMA_auto_pc_1} -quiet] -quiet

# IP: bd/DoubleDMA/ip/DoubleDMA_ps7_0_axi_periph_0/DoubleDMA_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DoubleDMA_ps7_0_axi_periph_0 || ORIG_REF_NAME==DoubleDMA_ps7_0_axi_periph_0} -quiet] -quiet

# XDC: e:/Vivado/Project_Vivado/DoubleDMA/DoubleDMA.gen/sources_1/bd/DoubleDMA/DoubleDMA_ooc.xdc
